name: Agones
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7.x

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push aimmo-game
        id: aimmo-game
        uses: docker/build-push-action@v2
        with:
          context: aimmo-game
          tags: ocadotechnology/aimmo-game:agones
          push: true
      - name: Build and push aimmo-game-creator
        id: aimmo-game-creator
        uses: docker/build-push-action@v2
        with:
          context: aimmo-game-creator
          tags: ocadotechnology/aimmo-game-creator:agones
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
